# theme: minima
remote_theme: pages-themes/hacker@v0.2.0
markdown: kramdown
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - BinaryTree.md
